#!/bin/bash
# SQL DDL Generator Script
# Generates CREATE TABLE statements for various database systems

set -e

# Default values
ENTITY_NAME="${1:-}"
DB_TYPE="${2:-postgresql}"
OUTPUT_DIR="${3:-.}"

# Validate input
if [ -z "$ENTITY_NAME" ]; then
    echo "Usage: bash generate-sql.sh <entity-name> [database-type] [output-dir]"
    echo "  entity-name: Entity name (PascalCase, e.g., User, Product)"
    echo "  database-type: postgresql (default), mysql, sqlite, mssql"
    echo "  output-dir: Output directory (default: current directory)"
    exit 1
fi

# Convert PascalCase to snake_case for table name
to_snake_case() {
    echo "$1" | sed 's/\([a-z0-9]\)\([A-Z]\)/\1_\2/g' | tr '[:upper:]' '[:lower:]'
}

TABLE_NAME=$(to_snake_case "$ENTITY_NAME")

# Create output directory if needed
mkdir -p "$OUTPUT_DIR"

# Generate filename based on DB type
case "$DB_TYPE" in
    postgresql)
        FILE_EXT="sql"
        ;;
    mysql)
        FILE_EXT="mysql"
        ;;
    sqlite)
        FILE_EXT="sqlite"
        ;;
    mssql)
        FILE_EXT="mssql"
        ;;
    *)
        echo "Unsupported database type: $DB_TYPE"
        echo "Supported: postgresql, mysql, sqlite, mssql"
        exit 1
        ;;
esac

OUTPUT_FILE="${OUTPUT_DIR}/${TABLE_NAME}.${FILE_EXT}"

# Generate PostgreSQL DDL
generate_postgresql() {
    cat << EOF
-- Table: $TABLE_NAME
-- Generated by SQL DDL Generator

CREATE TABLE IF NOT EXISTS $TABLE_NAME (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by INTEGER,
    updated_by INTEGER,
    
    CONSTRAINT uq_${TABLE_NAME}_name UNIQUE (name)
);

-- Indexes
CREATE INDEX idx_${TABLE_NAME}_is_active ON $TABLE_NAME(is_active);
CREATE INDEX idx_${TABLE_NAME}_created_at ON $TABLE_NAME(created_at);

-- Comments
COMMENT ON TABLE $TABLE_NAME IS 'Entity table for $ENTITY_NAME';
COMMENT ON COLUMN $TABLE_NAME.id IS 'Primary key';
COMMENT ON COLUMN $TABLE_NAME.name IS 'Entity name';
COMMENT ON COLUMN $TABLE_NAME.description IS 'Entity description';
COMMENT ON COLUMN $TABLE_NAME.is_active IS 'Soft delete flag';
COMMENT ON COLUMN $TABLE_NAME.created_at IS 'Creation timestamp';
COMMENT ON COLUMN $TABLE_NAME.updated_at IS 'Last update timestamp';
EOF
}

# Generate MySQL DDL
generate_mysql() {
    cat << EOF
-- Table: $TABLE_NAME
-- Generated by SQL DDL Generator

CREATE TABLE IF NOT EXISTS $TABLE_NAME (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active TINYINT(1) DEFAULT 1 NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    created_by INT,
    updated_by INT,
    
    CONSTRAINT uq_${TABLE_NAME}_name UNIQUE (name),
    INDEX idx_${TABLE_NAME}_is_active (is_active),
    INDEX idx_${TABLE_NAME}_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Comments
ALTER TABLE $TABLE_NAME COMMENT = 'Entity table for $ENTITY_NAME';
EOF
}

# Generate SQLite DDL
generate_sqlite() {
    cat << EOF
-- Table: $TABLE_NAME
-- Generated by SQL DDL Generator

CREATE TABLE IF NOT EXISTS $TABLE_NAME (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    is_active INTEGER DEFAULT 1 NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by INTEGER,
    updated_by INTEGER
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_${TABLE_NAME}_is_active ON $TABLE_NAME(is_active);
CREATE INDEX IF NOT EXISTS idx_${TABLE_NAME}_created_at ON $TABLE_NAME(created_at);
EOF
}

# Generate SQL Server DDL
generate_mssql() {
    cat << EOF
-- Table: $TABLE_NAME
-- Generated by SQL DDL Generator

CREATE TABLE $TABLE_NAME (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    description NVARCHAR(MAX),
    is_active BIT DEFAULT 1 NOT NULL,
    created_at DATETIME2 DEFAULT GETDATE() NOT NULL,
    updated_at DATETIME2 DEFAULT GETDATE() NOT NULL,
    created_by INT,
    updated_by INT,
    
    CONSTRAINT uq_${TABLE_NAME}_name UNIQUE (name)
);

-- Indexes
CREATE NONCLUSTERED INDEX idx_${TABLE_NAME}_is_active ON $TABLE_NAME(is_active);
CREATE NONCLUSTERED INDEX idx_${TABLE_NAME}_created_at ON $TABLE_NAME(created_at);
EOF
}

# Generate based on database type
case "$DB_TYPE" in
    postgresql)
        generate_postgresql > "$OUTPUT_FILE"
        ;;
    mysql)
        generate_mysql > "$OUTPUT_FILE"
        ;;
    sqlite)
        generate_sqlite > "$OUTPUT_FILE"
        ;;
    mssql)
        generate_mssql > "$OUTPUT_FILE"
        ;;
esac

echo "Generated SQL DDL: $OUTPUT_FILE"
echo "Table name: $TABLE_NAME"
echo "Database type: $DB_TYPE"
