#!/bin/bash

# Report Generator Script
# Generates report templates for various frameworks and types

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Default values
REPORT_NAME=""
REPORT_TYPE="table"
FRAMEWORK="chartjs"
OUTPUT_DIR="."

# Usage function
usage() {
  echo "Usage: $0 <report-name> [report-type] [framework] [output-dir]"
  echo ""
  echo "Arguments:"
  echo "  report-name   Name of the report (PascalCase, e.g., SalesReport)"
  echo "  report-type   Type of report: table, chart, pdf, excel, dashboard (default: table)"
  echo "  framework     Framework to use (default: chartjs)"
  echo "                Tables: ag-grid, datatables"
  echo "                Charts: chartjs, echarts"
  echo "                PDF: itext, wkhtmltopdf, jasperreports"
  echo "                Excel: poi, exceljs"
  echo "  output-dir    Output directory (default: current directory)"
  echo ""
  echo "Examples:"
  echo "  $0 SalesReport table chartjs ./reports"
  echo "  $0 UserActivityReport chart echarts"
  echo "  $0 FinancialReport pdf jasperreports ./output"
  exit 1
}

# Parse arguments
if [ $# -lt 1 ]; then
  usage
fi

REPORT_NAME="$1"
REPORT_TYPE="${2:-table}"
FRAMEWORK="${3:-chartjs}"
OUTPUT_DIR="${4:-.}"

# Validate report name
if [[ ! "$REPORT_NAME" =~ ^[A-Z][a-zA-Z0-9]*$ ]]; then
  echo -e "${RED}Error: Report name must be PascalCase (e.g., SalesReport)${NC}"
  exit 1
fi

# Validate report type
case "$REPORT_TYPE" in
  table|chart|pdf|excel|dashboard) ;;
  *)
    echo -e "${RED}Error: Invalid report type: $REPORT_TYPE${NC}"
    echo "Valid types: table, chart, pdf, excel, dashboard"
    exit 1
    ;;
esac

# Create output directory
REPORT_DIR="$OUTPUT_DIR/$REPORT_NAME"
mkdir -p "$REPORT_DIR"

echo -e "${GREEN}Generating report: $REPORT_NAME${NC}"
echo "  Type: $REPORT_TYPE"
echo "  Framework: $FRAMEWORK"
echo "  Output: $REPORT_DIR"

# Generate based on framework
case "$FRAMEWORK" in
  chartjs)
    generate_chartjs_report
    ;;
  echarts)
    generate_echarts_report
    ;;
  ag-grid)
    generate_aggrid_report
    ;;
  datatables)
    generate_datatables_report
    ;;
  itext|wkhtmltopdf|jasperreports)
    generate_pdf_report
    ;;
  poi|exceljs)
    generate_excel_report
    ;;
  *)
    echo -e "${RED}Error: Unknown framework: $FRAMEWORK${NC}"
    exit 1
    ;;
esac

echo -e "${GREEN}Report generated successfully!${NC}"
echo "Files created in: $REPORT_DIR"

# Chart.js report generator
generate_chartjs_report() {
  cat > "$REPORT_DIR/${REPORT_NAME}.js" << 'EOF'
// @ts-check
/**
 * {REPORT_NAME} - Chart.js Report
 * Generated by ASDM Report Development Skill
 */

const {REPORT_NAME} = (function() {
  'use strict';

  // Default configuration
  const config = {
    chartType: 'bar',
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: true },
      tooltip: { enabled: true }
    }
  };

  // Sample data - replace with actual data source
  const defaultData = {
    labels: [],
    datasets: [{
      label: '{REPORT_NAME} Data',
      data: [],
      backgroundColor: 'rgba(54, 162, 235, 0.5)',
      borderColor: 'rgba(54, 162, 235, 1)',
      borderWidth: 1
    }]
  };

  /**
   * Initialize the chart
   * @param {string} canvasId - Canvas element ID
   * @param {Object} data - Chart data (optional)
   */
  function init(canvasId, data = defaultData) {
    const ctx = document.getElementById(canvasId);
    if (!ctx) {
      console.error('Canvas element not found:', canvasId);
      return null;
    }

    return new Chart(ctx, {
      type: config.chartType,
      data: data,
      options: config
    });
  }

  /**
   * Update chart data
   * @param {Object} chart - Chart instance
   * @param {Object} newData - New data to display
   */
  function updateData(chart, newData) {
    if (chart) {
      chart.data = newData;
      chart.update();
    }
  }

  /**
   * Change chart type
   * @param {Object} chart - Chart instance
   * @param {string} type - New chart type
   */
  function changeType(chart, type) {
    if (chart) {
      chart.config.type = type;
      chart.update();
    }
  }

  return {
    config,
    init,
    updateData,
    changeType
  };
})();
EOF

  sed -i "s/{REPORT_NAME}/$REPORT_NAME/g" "$REPORT_DIR/${REPORT_NAME}.js"

  cat > "$REPORT_DIR/${REPORT_NAME}.html" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$REPORT_NAME - Chart.js</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
  <div class="report-container">
    <h1>$REPORT_NAME</h1>
    <canvas id="chart"></canvas>
  </div>
  <script src="${REPORT_NAME}.js"></script>
  <script>
    const chart = ${REPORT_NAME}.init('chart');
  </script>
</body>
</html>
EOF
}

# ECharts report generator
generate_echarts_report() {
  cat > "$REPORT_DIR/${REPORT_NAME}.js" << 'EOF'
// @ts-check
/**
 * {REPORT_NAME} - ECharts Report
 * Generated by ASDM Report Development Skill
 */

const {REPORT_NAME} = (function() {
  'use strict';

  // Default configuration
  const config = {
    responsive: true,
    maintainAspectRatio: false,
    title: {
      text: '{REPORT_NAME}'
    },
    tooltip: { trigger: 'axis' },
    legend: { data: [] },
    xAxis: { type: 'category', data: [] },
    yAxis: { type: 'value' },
    series: []
  };

  // Sample data - replace with actual data source
  const defaultData = {
    legend: ['Sales'],
    xAxisData: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    seriesData: [
      { name: 'Sales', type: 'bar', data: [120, 200, 150, 80, 70] }
    ]
  };

  /**
   * Initialize the chart
   * @param {string} domId - DOM element ID
   * @param {Object} data - Chart data (optional)
   */
  function init(domId, data = defaultData) {
    const dom = document.getElementById(domId);
    if (!dom) {
      console.error('DOM element not found:', domId);
      return null;
    }

    const chart = echarts.init(dom);
    const options = JSON.parse(JSON.stringify(config));

    options.legend.data = data.legend;
    options.xAxis.data = data.xAxisData;
    options.series = data.seriesData;

    chart.setOption(options);
    return chart;
  }

  /**
   * Update chart data
   * @param {Object} chart - ECharts instance
   * @param {Object} newData - New data to display
   */
  function updateData(chart, newData) {
    if (chart) {
      chart.setOption({
        legend: { data: newData.legend },
        xAxis: { data: newData.xAxisData },
        series: newData.seriesData
      });
    }
  }

  return {
    config,
    init,
    updateData
  };
})();
EOF

  sed -i "s/{REPORT_NAME}/$REPORT_NAME/g" "$REPORT_DIR/${REPORT_NAME}.js"

  cat > "$REPORT_DIR/${REPORT_NAME}.html" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$REPORT_NAME - ECharts</title>
  <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
</head>
<body>
  <div class="report-container">
    <h1>$REPORT_NAME</h1>
    <div id="chart" style="width: 100%; height: 400px;"></div>
  </div>
  <script src="${REPORT_NAME}.js"></script>
  <script>
    const chart = ${REPORT_NAME}.init('chart');
  </script>
</body>
</html>
EOF
}

# AG Grid report generator
generate_aggrid_report() {
  cat > "$REPORT_DIR/${REPORT_NAME}.js" << 'EOF'
// @ts-check
/**
 * {REPORT_NAME} - AG Grid Report
 * Generated by ASDM Report Development Skill
 */

const {REPORT_NAME} = (function() {
  'use strict';

  // Default column definitions
  const defaultColumns = [
    { field: 'id', headerName: 'ID', width: 90, sortable: true, filter: true },
    { field: 'name', headerName: 'Name', width: 150, sortable: true, filter: true },
    { field: 'value', headerName: 'Value', width: 120, sortable: true, filter: 'agNumberColumnFilter' },
    { field: 'date', headerName: 'Date', width: 150, sortable: true }
  ];

  // Sample data - replace with actual data source
  const defaultData = [
    { id: 1, name: 'Item 1', value: 100, date: '2024-01-01' },
    { id: 2, name: 'Item 2', value: 200, date: '2024-01-02' },
    { id: 3, name: 'Item 3', value: 150, date: '2024-01-03' }
  ];

  // Grid options
  let gridOptions = null;

  /**
   * Initialize the grid
   * @param {string} gridDivId - Grid DIV element ID
   * @param {Array} data - Row data (optional)
   * @param {Array} columns - Column definitions (optional)
   */
  function init(gridDivId, data = defaultData, columns = defaultColumns) {
    gridOptions = {
      columnDefs: columns,
      rowData: data,
      defaultColDef: {
        resizable: true,
        sortable: true,
        filter: true
      },
      pagination: true,
      paginationPageSize: 20,
      rowSelection: 'multiple',
      animateRows: true
    };

    const gridDiv = document.getElementById(gridDivId);
    if (!gridDiv) {
      console.error('Grid DIV not found:', gridDivId);
      return null;
    }

    return new agGrid.Grid(gridDiv, gridOptions);
  }

  /**
   * Update grid data
   * @param {Array} newData - New row data
   */
  function updateData(newData) {
    if (gridOptions) {
      gridOptions.api.setRowData(newData);
    }
  }

  /**
   * Export to CSV
   */
  function exportCSV() {
    if (gridOptions) {
      gridOptions.api.exportDataAsCsv();
    }
  }

  /**
   * Get selected rows
   * @returns {Array} Selected row data
   */
  function getSelectedRows() {
    if (gridOptions) {
      return gridOptions.api.getSelectedRows();
    }
    return [];
  }

  return {
    init,
    updateData,
    exportCSV,
    getSelectedRows
  };
})();
EOF

  sed -i "s/{REPORT_NAME}/$REPORT_NAME/g" "$REPORT_DIR/${REPORT_NAME}.js"

  cat > "$REPORT_DIR/${REPORT_NAME}.html" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$REPORT_NAME - AG Grid</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ag-grid-community@30.0.0/styles/ag-grid.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ag-grid-community@30.0.0/styles/ag-theme-alpine.css">
  <script src="https://cdn.jsdelivr.net/npm/ag-grid-community@30.0.0/dist/ag-grid-community.min.js"></script>
</head>
<body>
  <div class="report-container">
    <h1>$REPORT_NAME</h1>
    <button onclick="${REPORT_NAME}.exportCSV()">Export CSV</button>
    <div id="grid" class="ag-theme-alpine" style="height: 400px; width: 100%;"></div>
  </div>
  <script src="${REPORT_NAME}.js"></script>
  <script>
    ${REPORT_NAME}.init('grid');
  </script>
</body>
</html>
EOF
}

# DataTables report generator
generate_datatables_report() {
  cat > "$REPORT_DIR/${REPORT_NAME}.js" << 'EOF'
// @ts-check
/**
 * {REPORT_NAME} - DataTables Report
 * Generated by ASDM Report Development Skill
 */

const {REPORT_NAME} = (function() {
  'use strict';

  // Sample data - replace with actual data source
  const defaultData = [
    [1, 'Item 1', 100, '2024-01-01'],
    [2, 'Item 2', 200, '2024-01-02'],
    [3, 'Item 3', 150, '2024-01-03']
  ];

  // Default columns
  const defaultColumns = [
    { title: 'ID' },
    { title: 'Name' },
    { title: 'Value' },
    { title: 'Date' }
  ];

  let table = null;

  /**
   * Initialize DataTable
   * @param {string} tableId - Table element ID
   * @param {Array} data - Row data (optional)
   * @param {Array} columns - Column definitions (optional)
   */
  function init(tableId, data = defaultData, columns = defaultColumns) {
    table = $(tableId).DataTable({
      data: data,
      columns: columns,
      paging: true,
      searching: true,
      ordering: true,
      info: true,
      responsive: true,
      dom: 'Bfrtip',
      buttons: [
        'copyHtml5',
        'excelHtml5',
        'pdfHtml5',
        'print'
      ]
    });
    return table;
  }

  /**
   * Update table data
   * @param {Array} newData - New row data
   */
  function updateData(newData) {
    if (table) {
      table.clear().rows.add(newData).draw();
    }
  }

  /**
   * Add new row
   * @param {Array} rowData - New row data
   */
  function addRow(rowData) {
    if (table) {
      table.row.add(rowData).draw();
    }
  }

  /**
   * Search table
   * @param {string} query - Search query
   */
  function search(query) {
    if (table) {
      table.search(query).draw();
    }
  }

  return {
    init,
    updateData,
    addRow,
    search
  };
})();
EOF

  sed -i "s/{REPORT_NAME}/$REPORT_NAME/g" "$REPORT_DIR/${REPORT_NAME}.js"

  cat > "$REPORT_DIR/${REPORT_NAME}.html" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$REPORT_NAME - DataTables</title>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
  <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
</head>
<body>
  <div class="report-container">
    <h1>$REPORT_NAME</h1>
    <table id="table" class="display" style="width: 100%;"></table>
  </div>
  <script src="${REPORT_NAME}.js"></script>
  <script>
    ${REPORT_NAME}.init('#table');
  </script>
</body>
</html>
EOF
}

# PDF report generator (template)
generate_pdf_report() {
  cat > "$REPORT_DIR/${REPORT_NAME}.java" << 'EOF'
/**
 * {REPORT_NAME} - PDF Report Generator
 * Generated by ASDM Report Development Skill
 * Framework: {FRAMEWORK}
 */

package com.example.reports;

import java.util.List;
import java.util.Map;

public class {REPORT_NAME}Report {
    
    /**
     * Generate PDF report
     * @param data Report data
     * @param outputPath Output file path
     */
    public void generate(List<Map<String, Object>> data, String outputPath) {
        // TODO: Implement PDF generation using {FRAMEWORK}
        // 1. Create document
        // 2. Add header
        // 3. Add table/data
        // 4. Add footer
        // 5. Save to outputPath
    }
    
    /**
     * Generate PDF with template
     * @param templatePath Template file path
     * @param data Report data
     * @param outputPath Output file path
     */
    public void generateWithTemplate(String templatePath, 
                                      Map<String, Object> data, 
                                      String outputPath) {
        // TODO: Implement template-based PDF generation
    }
}
EOF

  sed -i "s/{REPORT_NAME}/$REPORT_NAME/g; s/{FRAMEWORK}/$FRAMEWORK/g" "$REPORT_DIR/${REPORT_NAME}.java"

  cat > "$REPORT_DIR/README.md" << EOF
# $REPORT_NAME - PDF Report

## Framework: $FRAMEWORK

## Setup

Add dependency for $FRAMEWORK:

```xml
<!-- Maven dependency -->
<dependency>
    <groupId>com.example</groupId>
    <artifactId>{FRAMEWORK}</artifactId>
    <version>1.0.0</version>
</dependency>
```

## Usage

```java
{REPORT_NAME}Report report = new {REPORT_NAME}Report();
report.generate(data, "output/report.pdf");
```
EOF
}

# Excel report generator (template)
generate_excel_report() {
  cat > "$REPORT_DIR/${REPORT_NAME}.java" << 'EOF'
/**
 * {REPORT_NAME} - Excel Report Generator
 * Generated by ASDM Report Development Skill
 * Framework: {FRAMEWORK}
 */

package com.example.reports;

import java.util.List;
import java.util.Map;

public class {REPORT_NAME}Report {
    
    /**
     * Generate Excel report
     * @param data Report data
     * @param outputPath Output file path
     */
    public void generate(List<Map<String, Object>> data, String outputPath) {
        // TODO: Implement Excel generation using {FRAMEWORK}
        // 1. Create workbook
        // 2. Create sheet
        // 3. Add headers
        // 4. Add data rows
        // 5. Apply formatting
        // 6. Save to outputPath
    }
    
    /**
     * Generate Excel with multiple sheets
     * @param sheets Map of sheet name to data
     * @param outputPath Output file path
     */
    public void generateMultipleSheets(Map<String, List<Map<String, Object>>> sheets,
                                         String outputPath) {
        // TODO: Implement multi-sheet Excel generation
    }
}
EOF

  sed -i "s/{REPORT_NAME}/$REPORT_NAME/g; s/{FRAMEWORK}/$FRAMEWORK/g" "$REPORT_DIR/${REPORT_NAME}.java"

  cat > "$REPORT_DIR/README.md" << EOF
# $REPORT_NAME - Excel Report

## Framework: $FRAMEWORK

## Setup

Add dependency for $FRAMEWORK:

```xml
<!-- Maven dependency -->
<dependency>
    <groupId>com.example</groupId>
    <artifactId>{FRAMEWORK}</artifactId>
    <version>1.0.0</version>
</dependency>
```

## Usage

```java
{REPORT_NAME}Report report = new {REPORT_NAME}Report();
report.generate(data, "output/report.xlsx");
```
EOF
}
